### ISSUE TITLE
systemd-free

### ISSUE THREAD

**Issue by GreenLunar** [vcalv/qlipmon#3]
Hello,

I'm planning to migrate to Artix or Parabola.
I was wondering whether qlipmon would work also on systems without systemd installed.

Thanks

**Comment by vcalv** [comment]
Yes. Provided the server is running it will work.

systemd is just a nice way of accomplishing that on login.

Another one is running the server on xsession or in any other X startup script.

**Comment by GreenLunar** [comment]
Thank you
